### ISSUE TITLE
Add top-level GEMM module description in the README

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snax-gemm#9]
It is good practice, to add top module descriptions in the README. It should contain the following:

- Port descriptions
- Top-level module diagram
- Timing diagrams

**Comment by guilherme-paim** [comment]
Hi all,

Where is A, B, C?
Which parameter can I configure the bitwidth of each input?
Where is the accumulator?
The tiles don't have output? Where is the data output going?

I suggest using draw.io files, where we can edit directly in VSCode (Draw.io Integration).
Instead of having a monolithic PNG figure, each contributor can improve, or even reuse your figure.
Draw.io files also can be used to parse synthesis results, to get you information about the cost of each block of your design.

**Comment by xiaoling-yi** [comment]
Good suggestion! I will add it later on!

**Comment by JosseVanDelm** [comment]
You can also use `mermaid` diagrams which are rendered by github directly:
```
flowchart LR

A[Hard] -->|Text| B(Round)
B --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
```
```mermaid
flowchart LR

A[Hard] -->|Text| B(Round)
B --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
```
Or this more complex one!
```mermaid
graph TD
 linkStyle default interpolate basis
 wan1[<center>DSL 100/10 Mb<br><br>10.100.102.1</center>]---router{<center>EdgeRouter-X<br><br>10.20.30.1</center>}
 ip((<center><br>IP<br><br></center>))-.-router
 dns((<center><br>DNS<br><br></center>))-.-router
 wan2[<center>LTE 50/20 Mb<br><br>192.168.1.1</center>]---router
 router---|100Mb|ap[<center>RT-AC1200<br><br>10.20.30.3</center>]
 router---|1Gb|pc(<center>PC<br><br>10.20.30.190</center>)
 router---|1Gb|switch[<center>TL-SG105E<br><br>10.20.30.2</center>]
 subgraph red1
 ap-.-cam1(<center>Camera<br><br>10.20.30.171</center>)
 ap-.-cam2(<center>Camera<br><br>10.20.30.172</center>)
 ap-.-phone(<center>Phone<br><br>10.20.30.191</center>)
 ap-.-ir(<center>IR<br><br>10.20.30.180</center>)
 end
 subgraph red2
 switch---|100Mb|pi1(<center>RPi 3B<br><br>10.20.30.150</center>)
 switch---|1Gb|pi2(<center>RPi 3B+<br><br>10.20.30.151</center>)
 switch---|100Mb|nvr(<center>NVR<br><br>10.20.30.170</center>)
 switch---|1Gb|laptop(<center>Laptop<br><br>10.20.30.192</center>)
 end
 ```

**Comment by xiaoling-yi** [comment]
The Port descriptions are added in this RP[](https://github.com/KULeuven-MICAS/snax-gemm/pull/12).
